### ISSUE TITLE
Convert bootstrap to primer

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-manager#1]
The [Hub manager](https://github.com/datalayer/jupyter-manager/tree/main/src/jupyter/hub) relies on bootstrap, we need to convert that to primer

**Comment by echarles** [comment]
At the same time, it would be good to convert as much as `JavaScript` to `TypeScript` as possible.

**Comment by echarles** [comment]
@im-adithya I have removed uneeded deps https://github.com/datalayer/jupyter-manager/commit/2da45ef766cdcc451422af5620ab493743bdc108 and refactored the components folders https://github.com/datalayer/jupyter-manager/commit/c8253bacb6ec85e23a766e75ccd01eefb9176add

The group page still needs to be fixed.

<img width="231" alt="Screenshot 2023-05-09 at 22 40 29" src="https://github.com/datalayer/jupyter-manager/assets/226720/3872145a-9837-44f7-9b2e-d3b562ab2dbc">

Also, clicking on the breadcrumbs refreshes the complete page, it should not.

**Comment by im-adithya** [comment]
> Also, clicking on the breadcrumbs refreshes the complete page, it should not.

Let's do that in another PR/issue as that requires some thought on how we are going to proceed with the routes, and close this with #10 which marks the primer progress
